[project]
name = "aula-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "guardrails",
    "guardrails-ai>=0.2.7",
    "regex>=2024.11.6",
]
